// Public Routes
export const ROUTES = {
    LANDING: "/",
    HOME: "/home",
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    RENTALS: "/rentals",
    MAPS: "/maps",
    CHAT: "/chat",
    VOICE: "/voice",
    SCHEMES: "/schemes",
    PROFILE: "/profile",
    ORDERS: "/orders",
    DELIVERIES: "/deliveries",
    DELIVERY_DETAILS: "/deliveries/:id",
    DELIVERIES: "/deliveries",
    FARMER_DASHBOARD: "/farmer-dashboard",
    PRODUCT_DETAILS: "/product/:type/:id",
    CART: "/cart",
    WISHLIST: "/wishlist",
    NOTIFICATIONS: "/notifications",
    HELP: "/help",
    FEEDBACK: "/feedback",
    WEATHER: "/weather",
    GOVT: "/govt",
};
